%SOAL 4.1

A = [1 2 3 ; 2 1 1 ; 3 2 1]
B = [4 4 5 ; 6 1 2 ; 3 5 5]

%DETERMINAN MATRIKS A DAN B
C=det(A)
C=det(B)

%UKURAN MATRIKS A DAN B
C=size(A)
C=size(B)

%TRACE MATRIKS A DAN B
C=trace(A)
C=trace(B)

%NORM MATRIKS A DAN B
C=norm(A)
C=norm(B)

C=A+B
C=A-B
C=A*B
C=A.*B
C=A^2
C=A.^2

%TRANSPOSE MATRIKS A DAN B
C=A'
C=B'

C=A./B
C=A.\B
C=A/B

%INVERS MATRIS A DAN B
C=inv(A)
C=inv(B)

C=null(A)
C=orth(A)
C=rref(A)

%NILAI EIGEN MATRIKS A DAN B
C=eig(A)
C=eig(B)

%NILAI SINGULAR MATRIKS A DAN B
C=svd(A)
C=svd(B)

%NILAI MATRIKS SEGITIGA ATAS DARI MATRIKS A DAN B
C=triu(A)
C=triu(B)

%MATRIKS SEGITIGA BAWAH DARI MATRIKS A DAN B
C=tril(A)
C=tril(B)

%NILAI MAKSIMUM ELEMEN MATRIKS A DAN B
C=max(max(A))
C=max(max(B))

%NILAI MINIMUM ELEMEN MATRIKS A DAN B
C=min(min(A))
C=min(min(B))

%JUMLAH KOLOM ELEMEN MATRIKS A DAN B
C1=sum(A, 1)
C2=sum(A, 2)

%DIAGONAL MATRIKS A DAN B
C=diag(A)
C=diag(B)

%SOAL 4.2
%DENGAN MENGGUNAKAN MATLAB, BUATLAH

% MATRIKS IDENTITAS DENGAN DIMENSI 5X5
A=eye(5)

%MATRIKS DENGAN DIMENSI 3X3 DENGAN ELEMEN-ELEMEN SEMUANYA BERNILAI NOL
A=zeros(3,3)

%MATRIKS DENGAN DIMENSI 3X4 DENGAN ELEMEN-ELEMEN SEMUANYA BERNILAI SATU
A=ones(4,4)

%MATRIKS DENGAN DIMENSI 3X4 DIMANA ELEMEN-ELEMEN TERDISTRIBUSI ANTARA 0 DAN
%1 (DEFAULT N=M)
A=rand(3,4)

%MATRIKS DENGAN DIMENSI 3X4 DIMANA ELEMEN-ELEMEN TERDISTRIBUSI NORMAL
A=randn(3,4)

